language: python
sudo: false
cache: pip
python:
  - 2.7
  - 3.3
  - pypy
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run setup.py -q test
after_success:
  - coveralls
